### ISSUE TITLE
Version 0.80 crashes

### ISSUE THREAD

**Issue by ghost** [siovene/smarthome-demo#16] opened 2017-01-17 02:35 UTC
Hi Salvatore,

I tried using version 0.8 of the app on my Nexus 6P. Unfortunately it crashes as soon as I tap the refresh sensor discovery button. I deployed the latest ocf-server JS files in the Smart Home repository from here in our OCF Smart Home demo environment. Since I updated the sensors I can no longer get your app to work. Can you please take a look? Thanks!

**Comment by qiuzhong** [comment] 2017-01-17 02:44
Currently, this release can work with Android 5.x. In [issue#11](https://github.com/siovene/smart-home-control/issues/11) comments, we mentioned this bug. According to our test experience, it has nothing to do with the OCF server side. It's caused by a fatal error:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "./obj/local/armeabi-v7a/liboc.so" not found
```
on Android 6.0+

**Comment by siovene** [comment] 2017-01-17 13:24
Fixed in 0.8.1.

**Closed as completed by siovene** 2017-01-17 13:24 UTC

**Comment by qiuzhong** [comment] 2017-01-18 08:29
Verified. Tested on Nexus 5(Android 6.0.1), Nexus 6P(Android 6.0) and Nexus 9 (Android 7.0) for version v0.8.1, all passed.

**Comment by siovene** [comment] 2017-01-18 11:58
[v0.8.2](https://github.com/siovene/smart-home-control/releases/tag/v0.8.2) released and it seems quite stable to me!

**Comment by ghost** [comment] 2017-01-18 13:25
No APK for this version to be found under releases.
